schemes:
  miramare: &miramare
    # Default colors
    primary:
      background: '#2A2426'
      foreground: '#e6d6ac'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#e68183'
      green:   '#87af87'
      yellow:  '#d9bb80'
      blue:    '#89beba'
      magenta: '#d3a0bc'
      cyan:    '#87c095'
      white:   '#e4e4e4'

    # Bright colors
    bright:
      black:   '#626262'
      red:     '#d75f87'
      green:   '#87af87'
      yellow:  '#ffd787'
      blue:    '#add4fb'
      magenta: '#ffafaf'
      cyan:    '#87d7d7'
      white:   '#e4e4e4'

  seoul256_light: &seoul256-light
    # Default colors
    primary:
      background: '#E1E1E1'
      foreground: '#606060'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#af5f5f'
      green:   '#5f885f'
      yellow:  '#af8760'
      blue:    '#5f87ae'
      magenta: '#875f87'
      cyan:    '#5f8787'
      white:   '#e4e4e4'

    # Bright colors
    bright:
      black:   '#3a3a3a'
      red:     '#870100'
      green:   '#005f00'
      yellow:  '#d8865f'
      blue:    '#0087af'
      magenta: '#87025f'
      cyan:    '#008787'
      white:   '#eeeeee'

  seoul256_dark: &seoul256-dark
    # Default colors
    primary:
      background: '#4b4b4b'
      foreground: '#d0d0d0'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#d68787'
      green:   '#5f865f'
      yellow:  '#d8af5f'
      blue:    '#85add4'
      magenta: '#d7afaf'
      cyan:    '#87afaf'
      white:   '#d0d0d0'

    # Bright colors
    bright:
      black:   '#626262'
      red:     '#d75f87'
      green:   '#87af87'
      yellow:  '#ffd787'
      blue:    '#add4fb'
      magenta: '#ffafaf'
      cyan:    '#87d7d7'
      white:   '#e4e4e4'

  dracula: &dracula
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'

    # Bright colors
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'

  gruvbox_dark: &gruvbox-dark
    primary:
      # hard contrast: background = '0x1d2021'
      background: '0x282828'
      # soft contrast: background = '0x32302f'
      foreground: '0xebdbb2'
    normal:
      black:   '0x282828'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0xa89984'
    bright:
      black:   '0x928374'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xebdbb2'

  gruvbox_light: &gruvbox-light
    primary:
      # hard contrast: background = '0xf9f5d7'
      background: '0xfbf1c7'
      # soft contrast: background = '0xf2e5bc'
      foreground: '0x3c3836'
    normal:
      black:   '0xfbf1c7'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0x7c6f64'
    bright:
      black:   '0x928374'
      red:     '0x9d0006'
      green:   '0x79740e'
      yellow:  '0xb57614'
      blue:    '0x076678'
      magenta: '0x8f3f71'
      cyan:    '0x427b58'
      white:   '0x3c3836'

  rose_pine_moon: &rose-pine-dark
    primary:
      background: '0x232136'
      foreground: '0xe0def4'
    cursor:
      text: '0xe0def4'
      cursor: '0x56526e'
    vi_mode_cursor:
      text: '0xe0def4'
      cursor: '0x56526e'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: '0xe0def4'
      background: '0x44415a'
    normal:
      black: '0x393552'
      red: '0xeb6f92'
      green: '0x3e8fb0'
      yellow: '0xf6c177'
      blue: '0x9ccfd8'
      magenta: '0xc4a7e7'
      cyan: '0xea9a97'
      white: '0xe0def4'
    bright:
      black: '0x6e6a86'
      red: '0xeb6f92'
      green: '0x3e8fb0'
      yellow: '0xf6c177'
      blue: '0x9ccfd8'
      magenta: '0xc4a7e7'
      cyan: '0xea9a97'
      white: '0xe0def4'
    hints:
      start:
        foreground: '#908caa'
        background: '#2a273f'
      end:
        foreground: '#6e6a86'
        background: '#2a273f'

  rose_pine_dawn: &rose-pine-light
    primary:
      background: '0xfaf4ed'
      foreground: '0x575279'
    cursor:
      text: '0x575279'
      cursor: '0xcecacd'
    vi_mode_cursor:
      text: '0x575279'
      cursor: '0xcecacd'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: '0x575279'
      background: '0xdfdad9'
    normal:
      black: '0xf2e9e1'
      red: '0xb4637a'
      green: '0x286983'
      yellow: '0xea9d34'
      blue: '0x56949f'
      magenta: '0x907aa9'
      cyan: '0xd7827e'
      white: '0x575279'
    bright:
      black: '0x9893a5'
      red: '0xb4637a'
      green: '0x286983'
      yellow: '0xea9d34'
      blue: '0x56949f'
      magenta: '0x907aa9'
      cyan: '0xd7827e'
      white: '0x575279'
    hints:
      start:
        foreground: '#797593'
        background: '#fffaf3'
      end:
        foreground: '#9893a5'
        background: '#fffaf3'

  catppuccin: &catppuccin
    # Default colors
    primary:
      background: '0x1E1D2F'
      foreground: '0xD9E0EE'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1E1D2F'
      cursor: '0xF5E0DC'

    # Normal colors
    normal:
      black:   '0x6E6C7E'
      red:     '0xF28FAD'
      green:   '0xABE9B3'
      yellow:  '0xFAE3B0'
      blue:    '0x96CDFB'
      magenta: '0xF5C2E7'
      cyan:    '0x89DCEB'
      white:   '0xD9E0EE'

    # Bright colors
    bright:
      black:   '0x988BA2'
      red:     '0xF28FAD'
      green:   '0xABE9B3'
      yellow:  '0xFAE3B0'
      blue:    '0x96CDFB'
      magenta: '0xF5C2E7'
      cyan:    '0x89DCEB'
      white:   '0xD9E0EE'

    indexed_colors:
      - { index: 16, color: '0xF8BD96' }
      - { index: 17, color: '0xF5E0DC' }

colors: *rose-pine-light
