schemes:
  miramare: &miramare
    # Default colors
    primary:
      background: '#2A2426'
      foreground: '#e6d6ac'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#e68183'
      green:   '#87af87'
      yellow:  '#d9bb80'
      blue:    '#89beba'
      magenta: '#d3a0bc'
      cyan:    '#87c095'
      white:   '#e4e4e4'

    # Bright colors
    bright:
      black:   '#626262'
      red:     '#d75f87'
      green:   '#87af87'
      yellow:  '#ffd787'
      blue:    '#add4fb'
      magenta: '#ffafaf'
      cyan:    '#87d7d7'
      white:   '#e4e4e4'

  seoul256_light: &seoul256-light
    # Default colors
    primary:
      background: '#E1E1E1'
      foreground: '#606060'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#af5f5f'
      green:   '#5f885f'
      yellow:  '#af8760'
      blue:    '#5f87ae'
      magenta: '#875f87'
      cyan:    '#5f8787'
      white:   '#e4e4e4'

    # Bright colors
    bright:
      black:   '#3a3a3a'
      red:     '#870100'
      green:   '#005f00'
      yellow:  '#d8865f'
      blue:    '#0087af'
      magenta: '#87025f'
      cyan:    '#008787'
      white:   '#eeeeee'

  seoul256_dark: &seoul256
    # Default colors
    primary:
      background: '#4b4b4b'
      foreground: '#d0d0d0'

    # Normal colors
    normal:
      black:   '#4e4e4e'
      red:     '#d68787'
      green:   '#5f865f'
      yellow:  '#d8af5f'
      blue:    '#85add4'
      magenta: '#d7afaf'
      cyan:    '#87afaf'
      white:   '#d0d0d0'

    # Bright colors
    bright:
      black:   '#626262'
      red:     '#d75f87'
      green:   '#87af87'
      yellow:  '#ffd787'
      blue:    '#add4fb'
      magenta: '#ffafaf'
      cyan:    '#87d7d7'
      white:   '#e4e4e4'

  dracula: &dracula
    # Default colors
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'

    # Bright colors
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'

  gruvbox_dark: &gruvbox
    primary:
      # hard contrast: background = '0x1d2021'
      background: '0x282828'
      # soft contrast: background = '0x32302f'
      foreground: '0xebdbb2'
    normal:
      black:   '0x282828'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0xa89984'
    bright:
      black:   '0x928374'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xebdbb2'

  gruvbox_light: &gruvbox-light
    primary:
      # hard contrast: background = '0xf9f5d7'
      background: '0xfbf1c7'
      # soft contrast: background = '0xf2e5bc'
      foreground: '0x3c3836'
    normal:
      black:   '0xfbf1c7'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0x7c6f64'
    bright:
      black:   '0x928374'
      red:     '0x9d0006'
      green:   '0x79740e'
      yellow:  '0xb57614'
      blue:    '0x076678'
      magenta: '0x8f3f71'
      cyan:    '0x427b58'
      white:   '0x3c3836'

colors: *miramare
