#!/usr/bin/env sh

spacebar -m config position           bottom
spacebar -m config height             15
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "SFMono Nerd Font:Regular:10.0"
spacebar -m config icon_font          "SFMono Nerd Font:Regular:12.0"
spacebar -m config background_color   0xff202020
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xff775759
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xff458588
spacebar -m config space_icon_strip       礼 
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%a %d/%m/%y %R"

SPACES="ﰍ ﴬ     7 8 9 10 11 12 13 14 15 16 0"
