#######################
# envs
#######################

asdf:

perl:
  mode: local
  version: 5.36.0

python:
  mode: local
  version: 3.8.10

python-env:
  virtualenv:

golang:
  mode: local
  version: 1.19.13

rust:
  mode: local
  version: 1.70.0

nodejs:
  mode: local
  version: 17.9.1  # glibc 2.27 compatible

lua:
  mode: local
  version: 5.4.3


#######################
# apps & libs
#######################

zsh:

prezto:

neovim:

tmux:

wget:

tree:

fd:

rg:

tldr:

up:

jq:

sox:

tcpdump:

#######################
# dots
#######################

bins:
  mode: local

configs:
  mode: local

tpm:
  mode: local

tmux-plugins:
  mode: local

neovim-plugins:
  mode: local

neovim-providers:
  mode: local
