help2man:
  install: true
  local: false
  force: false

pkg_config:
  install: true
  local: false
  force: false

ncurses:
  install: true
  local: false
  force: false

openssl:
  install: true
  local: false
  force: false

libevent:
  install: true
  local: false
  force: false

m4:
  install: true
  local: false
  force: false

autoconf:
  install: true
  local: false
  force: false

automake:
  install: true
  local: false
  force: false

libtool:
  install: true
  local: false
  force: false

gettext:
  install: true
  local: false
  force: false

patch:
  install: true
  local: false
  force: false

readline:
  install: true
  local: false
  force: false

zlib:
  install: true
  local: false
  force: false

bzip2:
  install: true
  local: false
  force: false

sqlite3:
  install: true
  local: false
  force: false

libffi:
  install: true
  local: false
  force: false

gmp:
  install: true
  local: false
  force: false

libnettle:
  install: true
  local: false
  force: false

libtasn1:
  install: true
  local: false
  force: false

p11_kit:
  install: true
  local: false
  force: false

gnutls:
  install: true
  local: false
  force: false

libgpg_error:
  install: true
  local: false
  force: false

libgcrypt:
  install: true
  local: false
  force: false

libassuan:
  install: true
  local: false
  force: false

libksba:
  install: true
  local: false
  force: false

npth:
  install: true
  local: false
  force: false

gnupg:
  install: true
  local: false
  force: false

xorgproto:
  install: true
  local: false
  force: false

xtrans:
  install: true
  local: false
  force: false

libxau:
  install: true
  local: false
  force: false

xcb_proto:
  install: true
  local: false
  force: false

libxcb:
  install: true
  local: false
  force: false

libx11:
  install: true
  local: false
  force: false

tcl:
  install: true
  local: false
  force: false

tk:
  install: true
  local: false
  force: false

boost:
  install: true
  local: false
  force: false

liblzma:
  install: true
  local: false
  force: false

######################

pyenv:
  install: false
  local: false
  force: false

goenv:
  install: false
  local: false
  force: false

asdf:
  install: true
  local: false
  force: true

#######################

python2:
  install: true
  version: 2.7.18

python3:
  install: true
  version: 3.8.5

python_black:
  install: true

python_isort:
  install: true

python_flake8:
  install: true

golang:
  install: true
  version: 1.17.5

rust:
  install: true
  version: 1.57.0

nodejs:
  install: true
  version: 17.2.0

lua:
  install: true
  version: 5.4.3

lua_stylua:
  install: true

sh_shellcheck:
  install: true

sh_shfmt:
  install: true

#######################

terminfo:
  install: true

unzip:
  install: true
  local: false
  force: false

gzip:
  install: true
  local: false
  force: false

zsh:
  install: true
  local: false
  force: true

fish:
  install: false
  local: false
  force: true

prezto:
  install: true
  force: true

neovim:
  install: true
  local: false
  force: true
  version: stable

tmux:
  install: true
  local: false
  force: true

#######################

tree:
  install: true
  local: false
  force: true

fd:
  install: true
  local: false
  force: true

rg:
  install: true
  local: false
  force: true

thefuck:
  install: true
  local: false
  force: true

ranger:
  install: false
  force: true

tldr:
  install: true
  local: false
  force: true

bash_snippets:
  install: true
  local: false
  force: true

bpytop:
  install: false
  local: false
  force: true

up:
  install: true
  local: false
  force: true

#######################

change_default_shell:
  change: true
  local: false
  shell: zsh

#######################
