help2man:
  install: true
  local: true
  force: false

pkg_config:
  install: true
  local: true
  force: false

ncurses:
  install: true
  local: true
  force: false

openssl:
  install: true
  local: true
  force: false

libevent:
  install: true
  local: true
  force: false

m4:
  install: true
  local: true
  force: false

autoconf:
  install: true
  local: true
  force: false

automake:
  install: true
  local: true
  force: false

libtool:
  install: true
  local: true
  force: false

gettext:
  install: true
  local: true
  force: false

patch:
  install: true
  local: true
  force: false

readline:
  install: true
  local: true
  force: false

zlib:
  install: true
  local: true
  force: false

bzip2:
  install: true
  local: true
  force: false

sqlite3:
  install: true
  local: true
  force: false

libffi:
  install: true
  local: true
  force: false

gmp:
  install: true
  local: true
  force: false

libnettle:
  install: true
  local: true
  force: false

libtasn1:
  install: true
  local: true
  force: false

p11_kit:
  install: true
  local: true
  force: false

gnutls:
  install: true
  local: true
  force: false

libgpg_error:
  install: true
  local: true
  force: false

libgcrypt:
  install: true
  local: true
  force: false

libassuan:
  install: true
  local: true
  force: false

libksba:
  install: true
  local: true
  force: false

npth:
  install: true
  local: true
  force: false

gnupg:
  install: true
  local: true
  force: false

xorgproto:
  install: true
  local: true
  force: false

xtrans:
  install: true
  local: true
  force: false

libxau:
  install: true
  local: true
  force: false

xcb_proto:
  install: true
  local: true
  force: false

libxcb:
  install: true
  local: true
  force: false

libx11:
  install: true
  local: true
  force: false

tcl:
  install: true
  local: true
  force: false

tk:
  install: true
  local: true
  force: false

boost:
  install: true
  local: true
  force: false

######################

pyenv:
  install: false
  local: true
  force: false

goenv:
  install: false
  local: true
  force: false

asdf:
  install: true
  local: true
  force: false

shellcheck:
  install: true
  local: true
  force: true

#######################

python2:
  install: true
  version: latest

python3:
  install: true
  version: latest

golang:
  install: true
  version: latest

rust:
  install: true
  version: latest

nodejs:
  install: true
  version: latest

#######################

terminfo:
  install: true

zsh:
  install: true
  local: true
  force: true

fish:
  install: false
  local: true
  force: true

prezto:
  install: true
  force: true

neovim:
  install: true
  local: true
  force: true
  version: stable

tmux:
  install: true
  local: true
  force: true

tpm:
  install: true
  local: true
  force: true

#######################

tree:
  install: true
  local: true
  force: true

fd:
  install: true
  local: true
  force: true

rg:
  install: true
  local: true
  force: true

thefuck:
  install: true
  local: true
  force: true

ranger:
  install: false
  force: true

tldr:
  install: true
  local: true
  force: true

bash_snippets:
  install: true
  local: true
  force: true

bpytop:
  install: true
  local: true
  force: true

up:
  install: true
  local: true
  force: true

highlight:
  install: true
  local: true
  force: true

#######################

change_default_shell:
  change: true
  local: true
  shell: zsh

#######################
