zsh:
  install: yes
  local: yes

changeDefaultShell:
  change: yes
  local: yes

prezto:
  install: yes

nvim:
  install: yes
  local: yes

tmux:
  install: yes
  local: yes

bins:
  tree:
    install: yes
    local: yes
  fd:
    install: yes
    local: yes
  rg:
    install: yes
    local: yes
  thefuck:
    install: no
    local: yes
  ranger:
    install: yes
    local: yes
  bash_snippets:
    install: yes
    local: yes
