zsh:
  install: yes
  local: yes
  force: yes

changeDefaultShell:
  change: yes
  local: yes

prezto:
  install: yes

nvim:
  install: yes
  local: yes
  force: yes

tmux:
  install: yes
  local: yes
  force: yes

tree:
  install: yes
  local: yes
  force: yes

fd:
  install: yes
  local: yes
  force: yes

rg:
  install: yes
  local: yes
  force: yes

thefuck:
  install: yes
  local: yes
  force: yes

ranger:
  install: yes
  force: yes

tldr:
  install: yes
  local: yes
  force: yes

bash_snippets:
  install: yes
  local: yes
  force: yes

shellcheck:
  install: yes
  local: yes
  force: yes

bash_language_server:
  install: yes
  force: yes

nodejs:
  install: yes
  force: no

pyenv:
  install: yes
  force: no

ccls:
  install: no
  force: yes
