#######################
# envs
#######################

asdf:

perl:
  version: 5.36.0

python:
  version: 3.8.10

python-env:
  virtualenv:

golang:
  version: 1.17.5

rust:
  version: 1.65.0

nodejs:
  version: 19.0.0

lua:
  version: 5.4.3


#######################
# apps & libs
#######################

zsh:

prezto:

neovim:

tmux:

wget:

tree:

fd:

rg:

tldr:

up:

jq:

sox:

tcpdump:

#######################
# dots
#######################

bins:
  mode: local

configs:
  mode: local

tpm:
  mode: local

tmux-plugins:
  mode: local

neovim-plugins:
  mode: local

neovim-providers:
  mode: local
