#######################
# installZsh
#######################

zsh:
  install: true
  local: true
  force: true

changeDefaultShell:
  change: true
  local: true
  force: true

#######################
# installPrezto
#######################

prezto:
  install: true
  force: true

#######################
# installNeovim
#######################

nvim:
  install: true
  local: true
  force: true

#######################
# installTmux
#######################

tmux:
  install: true
  local: true
  force: true

#######################
# installTree
#######################

tree:
  install: true
  local: true
  force: true

#######################
# installFd
#######################

fd:
  install: true
  local: true
  force: true

#######################
# installRg
#######################

rg:
  install: true
  local: true
  force: true

#######################
# installThefuck
#######################

thefuck:
  install: true
  local: true
  force: true

#######################
# installRanger
#######################

ranger:
  install: true
  force: true

#######################
#  installTldr
#######################

tldr:
  install: true
  local: true
  force: true

#######################
#  installBashSnippets
#######################

bash_snippets:
  install: true
  local: true
  force: true

#######################
# installDevshell
#######################

shellcheck:
  install: true
  local: true
  force: true

bash-language-server:
  install: true
  force: true

#######################
# installDevNodejs
#######################

node:
  install: true
  local: true
  force: false

yarn:
  install: false
  local: true
  force: false

#######################
# installDevPython
#######################

pyenv:
  install: true
  local: true
  force: false

# install pyenv python2 and python3
python2:
  install: true

python3:
  install: true

#######################
# installDevGo
#######################

goenv:
  install: true
  local: true
  force: false

# install goenv golang
go:
  install: true

#######################
# installDevC
#######################

ccls:
  install: false
  force: true
