#######################
# installZsh
#######################

zsh:
  install: true
  local: false
  force: true

#######################
# installFish
#######################

fish:
  install: false
  local: false
  force: true

#######################
# changeDefaultShell
#######################

changeDefaultShell:
  change: true
  local: false
  shell: zsh

#######################
# installPrezto
#######################

prezto:
  install: true
  force: true

#######################
# installNeovim
#######################

nvim:
  install: true
  local: false
  force: true

#######################
# installTmux
#######################

tmux:
  install: true
  local: false
  force: true

#######################
# installTree
#######################

tree:
  install: true
  local: false
  force: true

#######################
# installFd
#######################

fd:
  install: true
  local: false
  force: true

#######################
# installRg
#######################

rg:
  install: true
  local: false
  force: true

#######################
# installThefuck
#######################

thefuck:
  install: true
  local: false
  force: true

#######################
# installRanger
#######################

ranger:
  install: true
  force: true

#######################
#  installTldr
#######################

tldr:
  install: true
  local: false
  force: true

#######################
#  installBashSnippets
#######################

bash_snippets:
  install: true
  local: false
  force: true

#######################
# installDevshell
#######################

shellchecker:
  install: true
  local: false
  force: true

bash_language_server:
  install: true
  force: true

#######################
# installDevNodejs
#######################

node:
  install: true
  local: false
  force: false

yarn:
  install: false
  local: false
  force: false

#######################
# installDevAsdf
#######################

asdf:
  install: true
  local: true
  force: false

#######################
# installDevPython
#######################

pyenv:
  install: false
  local: false
  force: false

# install python2, python3
python2:
  install: true

python3:
  install: true

#######################
# installDevGo
#######################

goenv:
  install: false
  local: false
  force: false

# install golang
go:
  install: true

#######################
# installDevC
#######################

ccls:
  install: false
  force: true
