colors:
  background_color: '2a2426'
  white: 'd9d8d4'
  red: 'e68183'
  green: '87af87'
  yellow: 'd9bb80'
  blue: '86ad9e'
  pink: 'ffdfdf'
  cyan: '89beba'

  black: '4e4e4e'
  gray: '626262'
  darkgray: '666666'
  darkergray: '333333'

core:
  regular_file: {}

  directory:
    foreground: blue

  executable_file:
    foreground: red
    font-style: bold

  symlink:
    foreground: pink

  broken_symlink:
    foreground: black
    background: red
  missing_symlink_target:
    foreground: black
    background: red

  fifo:
    foreground: black
    background: blue

  socket:
    foreground: black
    background: pink

  character_device:
    foreground: pink
    background: darkergray

  block_device:
    foreground: cyan
    background: darkergray

  normal_text:
    {}

  other_writable:
    {}

  sticky:
    {}

  sticky_other_writable:
    {}

text:
  special:
    foreground: background_color
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: green

    continuous-integration:
      foreground: green

media:
  foreground: pink

office:
  foreground: red

archives:
  foreground: cyan
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: darkgray
