#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config external_bar                 all:0:15

# general space settings
# yabai -m config layout                       float
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   10

# Rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^KakaoTalk$" manage=off
yabai -m rule --add app="^Movist$" manage=off
yabai -m rule --add app="Transmission" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add app="Dictionary" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Window 10" space=3
yabai -m rule --add app="CleanMyMac X" manage=off

echo "yabai configuration loaded.."
