#!/usr/bin/env sh

#
# the scripting-addition must be loaded manually if
# one is running yabai on macOS Big Sur.
# for this to work one must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

# if OS version is greater than big sur,
big_sur_version=11.0
if [ "$(printf '%s\n' "$(sw_vers -productVersion)" "$big_sur_version" | sort -V | head -n 1)" = "$big_sur_version" ]; then
  yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
  sudo yabai --load-sa
fi

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_shadow                float
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config external_bar                 all:0:25

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# Rules
yabai -m rule --add app=".*" manage=off
# yabai -m rule --add app="^System Preferences$" manage=off
# yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add app="^App Store$" manage=off
# yabai -m rule --add app="^Activity Monitor$" manage=off
# yabai -m rule --add app="^KakaoTalk$" manage=off
# yabai -m rule --add app="^Movist$" manage=off
# yabai -m rule --add app="QuickTime Player" manage=off
# yabai -m rule --add app="Transmission" manage=off
# yabai -m rule --add app="Alfred Preferences" manage=off
# yabai -m rule --add app="Dictionary" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="Finder" manage=off
# yabai -m rule --add app="Window 10" space=3
# yabai -m rule --add app="CleanMyMac X" manage=off
# yabai -m rule --add app="Keka" manage=off
# yabai -m rule --add app="Stats" manage=off
# yabai -m rule --add app="Bartender" manage=off
# yabai -m rule --add title='Preferences$' manage=off topmost=on
# # https://github.com/koekeishiya/yabai/issues/322
# yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float'

yabai -m signal --add event=window_title_changed action="sketchybar --trigger window_title_changed"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focused"
yabai -m signal --add event=space_changed action="sketchybar --trigger space_changed"

echo "yabai configuration loaded.."
