#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

# if OS version is greater than big sur,
big_sur_version=11.0
if [ "$(printf '%s\n' $(sw_vers -productVersion) $big_sur_version | sort -V | head -n 1)" == $big_sur_version ]; then
    sudo yabai --load-sa
fi

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
# yabai -m config external_bar                 all:0:15

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# # signals
# # -- update active space in menu bar
# yabai -m signal --add event=space_changed \
#     action="open -g 'bitbar://refreshPlugin?name=yabai_layout.*?.sh'"

# Rules
yabai -m rule --add app=".*" manage=off
# yabai -m rule --add app="^System Preferences$" manage=off
# yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add app="^App Store$" manage=off
# yabai -m rule --add app="^Activity Monitor$" manage=off
# yabai -m rule --add app="^KakaoTalk$" manage=off
# yabai -m rule --add app="^Movist$" manage=off
# yabai -m rule --add app="QuickTime Player" manage=off
# yabai -m rule --add app="Transmission" manage=off
# yabai -m rule --add app="Alfred Preferences" manage=off
# yabai -m rule --add app="Dictionary" manage=off
# yabai -m rule --add app="^Calculator$" manage=off
# yabai -m rule --add app="Finder" manage=off
# yabai -m rule --add app="Window 10" space=3
# yabai -m rule --add app="CleanMyMac X" manage=off
# yabai -m rule --add app="Keka" manage=off
# yabai -m rule --add app="Stats" manage=off
# yabai -m rule --add app="Bartender" manage=off
# yabai -m rule --add title='Preferences$' manage=off topmost=on
# # https://github.com/koekeishiya/yabai/issues/322
# yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".resizable == 0 and .floating == 0" && yabai -m window $YABAI_WINDOW_ID --toggle float'

echo "yabai configuration loaded.."
