#!/usr/bin/env bash

curl --silent "https://api.github.com/repos/${1}/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                          # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                  # Pluck JSON value
