#!/usr/bin/env bash
# from https://stackoverflow.com/a/21189044

function parse_yaml {
  local prefix=$2
  echo "${prefix}TARGETS=()"
  local s='[[:space:]]*' w='[a-zA-Z0-9_-]*' fs=$(echo @|tr @ '\034')
  sed -ne "s|^\($s\):|\1|" \
       -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" $1 |
  awk -F$fs '{
     indent = length($1)/2;
     vname[indent] = $2;
     for (i in vname) {if (i > indent) {delete vname[i]}}
     printf("%sTARGETS+=(\"%s\")\n", "'$prefix'", vname[0]);
     if (length($3) > 0) {
        vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
        sub("-", "_", vn)
        printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
     }
  }'

  echo "${prefix}TARGETS=(\$(for v in \"\${${prefix}TARGETS[@]}\"; do echo \"\$v\";done| uniq))"
}

parse_yaml "$@"
