[colors.bright]
black = "#626262"
blue = "#add4fb"
cyan = "#87d7d7"
green = "#87af87"
magenta = "#ffafaf"
red = "#d75f87"
white = "#e4e4e4"
yellow = "#ffd787"

[colors.normal]
black = "#4e4e4e"
blue = "#89beba"
cyan = "#87c095"
green = "#87af87"
magenta = "#d3a0bc"
red = "#e68183"
white = "#e4e4e4"
yellow = "#d9bb80"

[colors.primary]
background = "#2A2426"
foreground = "#e6d6ac"
